# -*- coding: utf-8 -*-
"""translate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLKHeh9Ry7G4QY_ihpxOO5MK6oYMkvsu
"""

!pip install huggingface_hub

from huggingface_hub import InferenceClient

from google.colab import userdata
hugging_face_key = userdata.get('HF_TOKEN')

model_id = "Helsinki-NLP/opus-mt-en-hi"
client = InferenceClient(model=model_id, token= hugging_face_key)

hindi_translation = client.translation("Did you play cricket yesterday?")
print(hindi_translation)

